name: Deploy to gh-pages on push to main, check on pull requests

# See https://github.com/w3c/spec-prod/blob/main/docs/examples.md#deploy-to-github-pages

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          GH_PAGES_BUILD_OVERRIDE: |
            lint: false
          # W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          # W3C_WG_DECISION_URL: https://www.w3.org/WAI/GL/wiki/Decisions
          # W3C_BUILD_OVERRIDE: |
          #  specStatus: NOTE
          BUILD_FAIL_ON: everything
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: true
          VALIDATE_LINKS: true
          VALIDATE_MARKUP: true
